/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UrbnAgeVerification {
    /**
    * If `true`, the checkbox form will present, hiding the age dropdowns.
    */
    'checkboxOnly': boolean;
    /**
    * Minimum age that determines which years are available in the form.
    */
    'minimumAge': number;
    /**
    * Allows a translated list of dates to be passed into the component.
    */
    'months'?: Array<string>;
  }
}

declare global {


  interface HTMLUrbnAgeVerificationElement extends Components.UrbnAgeVerification, HTMLStencilElement {}
  var HTMLUrbnAgeVerificationElement: {
    prototype: HTMLUrbnAgeVerificationElement;
    new (): HTMLUrbnAgeVerificationElement;
  };
  interface HTMLElementTagNameMap {
    'urbn-age-verification': HTMLUrbnAgeVerificationElement;
  }
}

declare namespace LocalJSX {
  interface UrbnAgeVerification {
    /**
    * If `true`, the checkbox form will present, hiding the age dropdowns.
    */
    'checkboxOnly'?: boolean;
    /**
    * Minimum age that determines which years are available in the form.
    */
    'minimumAge'?: number;
    /**
    * Allows a translated list of dates to be passed into the component.
    */
    'months'?: Array<string>;
  }

  interface IntrinsicElements {
    'urbn-age-verification': UrbnAgeVerification;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'urbn-age-verification': LocalJSX.UrbnAgeVerification & JSXBase.HTMLAttributes<HTMLUrbnAgeVerificationElement>;
    }
  }
}


